FROM registry.cn-hangzhou.aliyuncs.com/shopex_company/ecshopex-php:7.4-fpm-alpine3.12

RUN apk --no-cache add ca-certificates tzdata \
        --repository https://mirrors.aliyun.com/alpine/v3.9/main/ && apk upgrade && apk add python3 && python3 -m ensurepip && python3 -m pip install supervisor -i https://mirrors.aliyun.com/pypi/simple

CMD ["php-fpm","-F"]

#RUN php composer.phar config repo.packagist composer https://mirrors.aliyun.com/composer/ \
#    && php composer.phar clear-cache \
#    && php composer.phar install -o \
#    && find . -name '\.git' | xargs rm -rf

#WORKDIR /data/httpd
#COPY  --from=builder /app .
#RUN rm -f .env.example .env.production .env.staging .env.star
#RUN mkdir /etc/supervisor.d

#RUN chown www-data:www-data -R ./storage 