FROM php:7.1-fpm

MAINTAINER ZoZhang <zo.zhang@gmail.com>

# Get repository and install wget and vim
RUN apt-get update && apt-get install --no-install-recommends -y \
        wget \
        vim \
        git \
        cron \
        unzip \
        procps \
        supervisor

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --install-dir=/usr/local/bin \
        --filename=composer

# Install PHP extensions deps
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        libkrb5-dev \
        libc-client-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libmcrypt4 \
        libcurl3-dev \
        libxslt1-dev \
        zlib1g-dev \
        libicu-dev \
        g++ \
        unixodbc-dev \
        libxml2-dev \
        libaio-dev \
        libmemcached-dev \
        freetds-dev \
        libssl-dev \
        openssl

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && pecl install redis memcached mailparse \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install \
            xml \
            exif \
            xsl \
            iconv \
            mbstring \
            intl \
            mcrypt \
            gd \
            mysqli \
            pdo_mysql \
            soap \
            sockets \
            zip \
            bcmath \
            pcntl \
            ftp \
            imap \
    && docker-php-ext-enable \
            memcached \
            opcache \
            mailparse 

# Custom enable php ext
RUN echo 'extension=redis.so' > /usr/local/etc/php/conf.d/docker-php-ext-redis.ini

# Install APCu and APC backward compatibility
RUN pecl install apcu \
    && pecl install apcu_bc-1.0.3 \
    && docker-php-ext-enable apcu --ini-name 10-docker-php-ext-apcu.ini \
    && docker-php-ext-enable apc --ini-name 20-docker-php-ext-apc.ini

# Install PHPUnit
RUN wget https://phar.phpunit.de/phpunit.phar -O /usr/local/bin/phpunit \
    && chmod +x /usr/local/bin/phpunit

RUN rm -rf /tmp/pear && apt-get clean && rm -rf /var/lib/apt/lists/* && usermod -u 1000 www-data

WORKDIR /var/www

COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT /entrypoint.sh

EXPOSE 9000