version: '2'

services:

### Application Container #######################################

    application:
        build: 
            context: ./application
        volumes:
           - ${TEMP_DIR}:/tmp/
           - ${APPLICATION}:/var/www
           - ${CRON_CONFIG_PATH}:/etc/cron.d/
           - ${CRON_LOG_PATH}:/var/log/cron/

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-${PHP_VERSION}
        volumes:    
            - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./php-fpm/custom.conf:/usr/local/etc/php-fpm.d/www.conf
        volumes_from:
            - application
        expose:
            - "9000"

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/extra/:/etc/nginx/extra/
        volumes_from:
            - application
        depends_on:
            - php-fpm      
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"

### Mariadb Container #########################################

    mariadb:
        build:
            context: ./mariadb
        #privileged: true
        user: mysql
        volumes:
            - ${MYSQL_DATADIR}:/var/lib/mysql
            #- ${MYSQL_CONF}:/etc/mysql/conf.d/my.cnf
            - ${MYSQL_HOST_LOG_PATH}:/var/log/mysql/
        ports:
            - "${MYSQL_PORT}:3306"

### Redis Container #########################################

    redis:
        build: ./redis
        volumes:
            - redis:/data
        ports:
            - "6379:6379"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes:
            - memcached:/var/lib/memcached
        ports:
            - "${MEMCACHED_HOST_PORT}:11211"

### Elasticsearch Container #######################################

    elasticsuite:
        build: ./elasticsuite
        ports:
            - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
            - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"

### Volumes Setup ###########################################

volumes:
    nginx:
        driver: "local"    
    mariadb:
        driver: "local"
    redis:
        driver: "local"
    memcached:
        driver: "local"
    elasticsuite:
        driver: "local"
    application:
        driver: "local"
