version: '2'

services:

### Application Container #######################################

    application:
        tty: true    
        build: 
            context: ./application
        volumes:
           - ${TEMP_DIR}:/tmp/
           - ${APPLICATION}:/var/www
           #- ${CRON_CONFIG_PATH}:/etc/cron.d/
           #- ${CRON_LOG_PATH}:/var/log/cron/

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-${PHP_VERSION}
        volumes:    
            - ${LICENSE_ECSHOPX}:/opt/ecshopx/license.zl
            - ./php-fpm/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/extra/ecshopx.ini:/usr/local/etc/php/conf.d/ecshopx.ini
            - ./php-fpm/extra/ecshopx.conf:/usr/local/etc/extra/ecshopx.conf
            - "socket:/var/run"
        volumes_from:
            - application

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
        volumes:
            - ./nginx/ssl/:/opt/ssl/
            - ./nginx/extra/:/etc/nginx/extra/
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/fastcgi_params:/etc/nginx/fastcgi_params
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - "socket:/var/run"
        volumes_from:
            - application 
        depends_on:
           - redis 
           - mariadb
           - php-fpm
        ports:
            - "8011:80"
            - "4311:443"
            - "8090:8090"
            - "8091:8091"

### Mariadb Container #########################################

    mariadb:
        build:
            context: ./mariadb
        #privileged: true
        user: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_DATADIR}:/var/lib/mysql
            - ${MYSQL_CONF}:/etc/mysql/my.cnf
            - ${MYSQL_HOST_LOG_PATH}:/var/log/mysql/
        ports:
            - "${MYSQL_PORT}:3306"

### Redis Container #########################################

    redis:
        build: ./redis
        volumes:
            - ./redis/redis.conf:/etc/redis.conf
        ports:
            - "${REDIS_HOST_PORT}:6379"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes:
            - memcached:/var/lib/memcached
        ports:
            - "${MEMCACHED_HOST_PORT}:11211"

### Elasticsearch Container #######################################

    elasticsuite:
        build: ./elasticsuite
        ports:
            - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
            - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"

### Volumes Setup ###########################################

volumes:
    socket:
    nginx:
        driver: "local"    
    mariadb:
        driver: "local"
    redis:
        driver: "local"
    memcached:
        driver: "local"
    elasticsuite:
        driver: "local"
    application:
        driver: "local"



